package com.tenahub.bot.entity;

public enum PharmacyPermission {
    INVENTORY_VIEW,
    INVENTORY_CREATE,
    INVENTORY_EDIT,
    INVENTORY_ADJUST,
    INVENTORY_ARCHIVE,

    PRESCRIPTION_VIEW,
    PRESCRIPTION_APPROVE,
    PRESCRIPTION_REJECT,

    RESERVATION_VIEW,
    RESERVATION_APPROVE,
    RESERVATION_FULFILL,
    RESERVATION_CANCEL,

    PRICE_VIEW,
    PRICE_EDIT,
    PRICE_BULK_UPDATE,
    PRICE_DISCOUNT,
    PRICE_APPROVE,

    SALES_VIEW,
    SALES_CREATE,
    SALES_REFUND,

    SUPPLIER_VIEW,
    SUPPLIER_CREATE,
    SUPPLIER_EDIT,

    PURCHASE_ORDER_VIEW,
    PURCHASE_ORDER_CREATE,
    PURCHASE_ORDER_APPROVE,
    PURCHASE_ORDER_RECEIVE,

    REPORT_VIEW,

    STAFF_VIEW,
    STAFF_CREATE,
    STAFF_EDIT,
    STAFF_DISABLE,
    STAFF_PERMISSION_MANAGE,

    AUDIT_VIEW,

    PHARMACY_SETTINGS_MANAGE
}
