package com.tenahub.bot.entity;

public enum PharmacyNotificationType {
    RESERVATION_PENDING,
    PRESCRIPTION_REVIEW,
    PRESCRIPTION_CLARIFICATION_REPLY,
    LOW_STOCK,
    EXPIRY,
    RESERVATION_SLA,
    PURCHASE_ORDER,
    PRICE_APPROVAL_REQUIRED,
    PRICE_APPROVED,
    PRICE_REJECTED,
    PRICE_ACTIVATED,
    PROMOTION_STARTED,
    PROMOTION_EXPIRED,
    STAFF_INVITED
}
