package com.tenahub.bot.registration;

public enum UpdateField {
    PHONE,
    LICENSE,
    HOURS,
    MEDICINES,
    LOCATION,
    INVENTORY_ADD,
    INVENTORY_BULK,
    INVENTORY_OUT,
    INVENTORY_PRESCRIPTION_SELECT,
    INVENTORY_THRESHOLD,
    PRICE,
    TEMP_CLOSE,
    PHOTO,
    PHOTO_ADD,
    PHOTO_SET_MAIN,
    PHOTO_REMOVE,
    MEDICINE_PHOTO_SELECT,
    MEDICINE_PHOTO_ADD,
    MEDICINE_PHOTO_SET_MAIN,
    MEDICINE_PHOTO_REMOVE
}